export const MOCK_SONGS = [
  {
    id: 1,
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: 200,
    image: 'https://via.placeholder.com/300x300?text=Blinding+Lights',
    likes: 5200000,
  },
  {
    id: 2,
    title: 'As It Was',
    artist: 'Harry Styles',
    album: 'Harry\'s House',
    duration: 173,
    image: 'https://via.placeholder.com/300x300?text=As+It+Was',
    likes: 4800000,
  },
  {
    id: 3,
    title: 'Anti-Hero',
    artist: 'Taylor Swift',
    album: 'Midnights',
    duration: 212,
    image: 'https://via.placeholder.com/300x300?text=Anti-Hero',
    likes: 5100000,
  },
  {
    id: 4,
    title: 'Heat Waves',
    artist: 'Glass Animals',
    album: 'Dreamland',
    duration: 239,
    image: 'https://via.placeholder.com/300x300?text=Heat+Waves',
    likes: 3900000,
  },
  {
    id: 5,
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: 203,
    image: 'https://via.placeholder.com/300x300?text=Levitating',
    likes: 4200000,
  },
];

export const MOCK_ARTISTS = [
  {
    id: 1,
    name: 'The Weeknd',
    image: 'https://via.placeholder.com/300x300?text=The+Weeknd',
    followers: 75000000,
  },
  {
    id: 2,
    name: 'Taylor Swift',
    image: 'https://via.placeholder.com/300x300?text=Taylor+Swift',
    followers: 88000000,
  },
  {
    id: 3,
    name: 'Drake',
    image: 'https://via.placeholder.com/300x300?text=Drake',
    followers: 68000000,
  },
  {
    id: 4,
    name: 'Ariana Grande',
    image: 'https://via.placeholder.com/300x300?text=Ariana+Grande',
    followers: 82000000,
  },
  {
    id: 5,
    name: 'Billie Eilish',
    image: 'https://via.placeholder.com/300x300?text=Billie+Eilish',
    followers: 61000000,
  },
];

export const MOCK_ALBUMS = [
  {
    id: 1,
    title: 'After Hours',
    artist: 'The Weeknd',
    image: 'https://via.placeholder.com/300x300?text=After+Hours',
    year: 2020,
    songs: 14,
  },
  {
    id: 2,
    title: 'Midnights',
    artist: 'Taylor Swift',
    image: 'https://via.placeholder.com/300x300?text=Midnights',
    year: 2022,
    songs: 13,
  },
  {
    id: 3,
    title: 'Certified Lover Boy',
    artist: 'Drake',
    image: 'https://via.placeholder.com/300x300?text=Certified+Lover+Boy',
    year: 2021,
    songs: 16,
  },
  {
    id: 4,
    title: 'Eternals',
    artist: 'Ariana Grande',
    image: 'https://via.placeholder.com/300x300?text=Eternals',
    year: 2022,
    songs: 12,
  },
  {
    id: 5,
    title: 'Happier Than Ever',
    artist: 'Billie Eilish',
    image: 'https://via.placeholder.com/300x300?text=Happier+Than+Ever',
    year: 2021,
    songs: 13,
  },
];

export const MOCK_PLAYLISTS = [
  {
    id: 1,
    name: 'Top Hits 2024',
    description: 'The biggest hits right now',
    image: 'https://via.placeholder.com/300x300?text=Top+Hits',
    songs: 50,
    followers: 500000,
  },
  {
    id: 2,
    name: 'Chill Vibes',
    description: 'Perfect for relaxation',
    image: 'https://via.placeholder.com/300x300?text=Chill+Vibes',
    songs: 75,
    followers: 320000,
  },
  {
    id: 3,
    name: 'Workout Energy',
    description: 'Get pumped for the gym',
    image: 'https://via.placeholder.com/300x300?text=Workout',
    songs: 60,
    followers: 450000,
  },
  {
    id: 4,
    name: 'Late Night Drive',
    description: 'Perfect for late night drives',
    image: 'https://via.placeholder.com/300x300?text=Late+Night',
    songs: 45,
    followers: 280000,
  },
  {
    id: 5,
    name: 'Indie Gems',
    description: 'Best indie tracks',
    image: 'https://via.placeholder.com/300x300?text=Indie+Gems',
    songs: 65,
    followers: 200000,
  },
];