// Mock Data for Development
import { ROUTES } from './index';

const mockImageUrl = 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=400&fit=crop';

export const MOCK_SONGS = [
  {
    id: 1,
    title: 'Midnight Dreams',
    artist: 'The Wanderers',
    album: 'Neon Nights',
    image: mockImageUrl,
    duration: 243,
    likes: 15420,
    url: '',
  },
  {
    id: 2,
    title: 'Sunset Boulevard',
    artist: 'Luna Echo',
    album: 'Golden Hour',
    image: mockImageUrl,
    duration: 287,
    likes: 12890,
    url: '',
  },
  {
    id: 3,
    title: 'Electric Pulse',
    artist: 'Neon Lights',
    album: 'Synthetic Dawn',
    image: mockImageUrl,
    duration: 215,
    likes: 18900,
    url: '',
  },
  {
    id: 4,
    title: 'Ocean Waves',
    artist: 'Coastal Breeze',
    album: 'By the Sea',
    image: mockImageUrl,
    duration: 265,
    likes: 9876,
    url: '',
  },
  {
    id: 5,
    title: 'Mountain Echo',
    artist: 'Alpine Sound',
    album: 'Heights',
    image: mockImageUrl,
    duration: 298,
    likes: 14567,
    url: '',
  },
  {
    id: 6,
    title: 'Urban Rhythm',
    artist: 'City Pulse',
    album: 'Metropolis',
    image: mockImageUrl,
    duration: 234,
    likes: 21043,
    url: '',
  },
];

export const MOCK_ALBUMS = [
  {
    id: 1,
    title: 'Neon Nights',
    artist: 'The Wanderers',
    image: mockImageUrl,
    year: 2023,
    songs: 12,
    followers: 89000,
  },
  {
    id: 2,
    title: 'Golden Hour',
    artist: 'Luna Echo',
    image: mockImageUrl,
    year: 2024,
    songs: 10,
    followers: 67000,
  },
  {
    id: 3,
    title: 'Synthetic Dawn',
    artist: 'Neon Lights',
    image: mockImageUrl,
    year: 2023,
    songs: 14,
    followers: 123000,
  },
  {
    id: 4,
    title: 'By the Sea',
    artist: 'Coastal Breeze',
    image: mockImageUrl,
    year: 2024,
    songs: 11,
    followers: 54000,
  },
  {
    id: 5,
    title: 'Heights',
    artist: 'Alpine Sound',
    image: mockImageUrl,
    year: 2023,
    songs: 13,
    followers: 76000,
  },
  {
    id: 6,
    title: 'Metropolis',
    artist: 'City Pulse',
    image: mockImageUrl,
    year: 2024,
    songs: 15,
    followers: 145000,
  },
];

export const MOCK_ARTISTS = [
  {
    id: 1,
    name: 'The Wanderers',
    image: mockImageUrl,
    followers: 345000,
  },
  {
    id: 2,
    name: 'Luna Echo',
    image: mockImageUrl,
    followers: 287000,
  },
  {
    id: 3,
    name: 'Neon Lights',
    image: mockImageUrl,
    followers: 521000,
  },
  {
    id: 4,
    name: 'Coastal Breeze',
    image: mockImageUrl,
    followers: 198000,
  },
  {
    id: 5,
    name: 'Alpine Sound',
    image: mockImageUrl,
    followers: 267000,
  },
  {
    id: 6,
    name: 'City Pulse',
    image: mockImageUrl,
    followers: 612000,
  },
];

export const MOCK_PLAYLISTS = [
  {
    id: 1,
    name: 'Chill Vibes',
    description: 'Relaxing music to unwind and de-stress',
    image: mockImageUrl,
    songs: 47,
    followers: 234000,
  },
  {
    id: 2,
    name: 'Workout Mix',
    description: 'High-energy tracks to pump up your fitness',
    image: mockImageUrl,
    songs: 52,
    followers: 187000,
  },
  {
    id: 3,
    name: 'Late Night Vibes',
    description: 'Perfect for late night sessions',
    image: mockImageUrl,
    songs: 38,
    followers: 156000,
  },
  {
    id: 4,
    name: 'Morning Coffee',
    description: 'Start your day with these uplifting tracks',
    image: mockImageUrl,
    songs: 43,
    followers: 201000,
  },
  {
    id: 5,
    name: 'Party Hits',
    description: 'Dancefloor favorites and club bangers',
    image: mockImageUrl,
    songs: 64,
    followers: 412000,
  },
  {
    id: 6,
    name: 'Focus Music',
    description: 'Concentration-boosting instrumental tracks',
    image: mockImageUrl,
    songs: 51,
    followers: 178000,
  },
];
